"""Layered configuration models, validation, merge, and snapshot hashing."""

from .canonical import CanonicalizationError, canonical_json_bytes, canonical_sha256
from .contracts import (
    CONFIG_LAYER_ORDER,
    ConfigLayer,
    ConfigMerger,
    ConfigSource,
    EffectiveBindings,
    EffectiveConfigSnapshot,
    EffectiveScope,
    EffectiveVersions,
    ExtensionPayload,
    ExtensionValidator,
    ProvenanceEntry,
    SafetyConstraints,
    SourceRecord,
)
from .merge import ConfigMergeError, DeterministicConfigMerger, snapshot_to_mapping
from .drafts import (
    ConfigDraftError,
    draft_channel_config,
    draft_concept_config,
    draft_episode_config,
)
from .models import (
    CHANNEL_CONFIG_ARTIFACT_VERSION,
    CONCEPT_CONFIG_ARTIFACT_VERSION,
    CONFIG_CONTRACT_VERSION,
    EFFECTIVE_CONFIG_ARTIFACT_VERSION,
    EPISODE_CONFIG_ARTIFACT_VERSION,
    WORKSPACE_CONFIG_ARTIFACT_VERSION,
    AspectRatio,
    ChannelConfig,
    ConceptConfig,
    ConfigValidationError,
    CoreSettings,
    EpisodeConfig,
    ExecutionSettings,
    IdentitySettings,
    LayerConfig,
    MediaSettings,
    WorkspaceConfig,
    config_document_from_mapping,
    config_document_values,
    config_source_from_document_bytes,
    normalize_config_values,
    parse_config_document,
)

__all__ = [
    "CHANNEL_CONFIG_ARTIFACT_VERSION",
    "CONCEPT_CONFIG_ARTIFACT_VERSION",
    "CONFIG_CONTRACT_VERSION",
    "CONFIG_LAYER_ORDER",
    "EFFECTIVE_CONFIG_ARTIFACT_VERSION",
    "EPISODE_CONFIG_ARTIFACT_VERSION",
    "WORKSPACE_CONFIG_ARTIFACT_VERSION",
    "AspectRatio",
    "CanonicalizationError",
    "ChannelConfig",
    "ConceptConfig",
    "ConfigDraftError",
    "ConfigLayer",
    "ConfigMergeError",
    "ConfigMerger",
    "ConfigSource",
    "ConfigValidationError",
    "CoreSettings",
    "DeterministicConfigMerger",
    "EffectiveBindings",
    "EffectiveConfigSnapshot",
    "EffectiveScope",
    "EffectiveVersions",
    "EpisodeConfig",
    "ExecutionSettings",
    "ExtensionPayload",
    "ExtensionValidator",
    "IdentitySettings",
    "LayerConfig",
    "MediaSettings",
    "ProvenanceEntry",
    "SafetyConstraints",
    "SourceRecord",
    "WorkspaceConfig",
    "canonical_json_bytes",
    "canonical_sha256",
    "config_document_from_mapping",
    "config_document_values",
    "config_source_from_document_bytes",
    "draft_channel_config",
    "draft_concept_config",
    "draft_episode_config",
    "normalize_config_values",
    "parse_config_document",
    "snapshot_to_mapping",
]
