"""Brand-entity projection models, round-trip evidence, and catalog ports."""

from .catalog import (
    BrandCatalog,
    CatalogEntity,
    CatalogSourceFormat,
    FixedSentenceExtractor,
    MarkdownBrandCatalog,
    MarkdownCatalogEntry,
    NonProductionEntityError,
    require_production_eligible,
)
from .models import (
    BRAND_ENTITY_ARTIFACT_VERSION,
    BrandData,
    BrandEntity,
    BrandEntityValidationError,
    CanonicalStatus,
    CharacterData,
    EntityKind,
    EntitySource,
    FixedSentence,
    LocationData,
    SourceSectionRange,
    entity_from_mapping,
    entity_to_mapping,
)
from .projection import (
    FieldComparison,
    FixedSentenceComparison,
    FixedSentenceObservation,
    MarkdownProjectionRenderer,
    OrderComparison,
    ProjectionField,
    ProjectionFormatError,
    ProjectionSnapshot,
    RoundTripChecker,
    RoundTripReport,
    entity_snapshot,
    rendered_snapshot,
)

__all__ = [
    "BRAND_ENTITY_ARTIFACT_VERSION",
    "BrandCatalog",
    "BrandData",
    "BrandEntity",
    "BrandEntityValidationError",
    "CanonicalStatus",
    "CatalogEntity",
    "CatalogSourceFormat",
    "CharacterData",
    "EntityKind",
    "EntitySource",
    "FieldComparison",
    "FixedSentence",
    "FixedSentenceComparison",
    "FixedSentenceExtractor",
    "FixedSentenceObservation",
    "LocationData",
    "MarkdownBrandCatalog",
    "MarkdownCatalogEntry",
    "MarkdownProjectionRenderer",
    "NonProductionEntityError",
    "OrderComparison",
    "ProjectionField",
    "ProjectionFormatError",
    "ProjectionSnapshot",
    "RoundTripChecker",
    "RoundTripReport",
    "SourceSectionRange",
    "entity_from_mapping",
    "entity_snapshot",
    "entity_to_mapping",
    "rendered_snapshot",
    "require_production_eligible",
]
