"""Concrete, fixture-only W06 runtime adapters.

This top-level package may perform local side effects.  The pure
``video_factory`` package must never import it.
"""

from .boundary import FixtureRuntimeBoundary, RuntimeBoundaryError
from .authority import (
    ClaimBoundAuthorizationLedger,
    ClaimBoundLedgerAdapter,
    FixtureAuthoritySettlementStore,
)
from .credentials import (
    CREDENTIAL_ATTESTATION_VERSION,
    CREDENTIAL_VERIFICATION_VERSION,
    CredentialLease,
    CredentialRuntimeError,
    CredentialScope,
    FixtureCredentialBroker,
    FixtureCredentialRegistration,
    OpaqueCredentialHandle,
    TrustedCredentialBroker,
    credential_scope_sha256,
    require_current_credential_lease,
)
from .filesystem import (
    CONTENT_EVIDENCE_VERSION,
    MANIFEST_VERSION,
    ContentAddressedFixtureStore,
    FixtureAtomicMutationPort,
    FixtureWorkspaceObserver,
    RuntimeFilesystemError,
    StableFile,
    fixture_manifest_sha256,
    read_stable_regular_file,
    read_stable_regular_bytes,
)
from .durable_execution import (
    RESULT_VERSION,
    DurableDispatchInputs,
    DurableExecutionError,
    DurableExecutorRuntime,
    FixtureExecutorPort,
    VerifiedExecutorInput,
    VerifiedExecutorInputBundle,
)
from .journal import (
    AuthorityReservationClaim,
    ExecutionJournalError,
    JournalSnapshot,
    SQLiteExecutionJournal,
    journal_event_reference,
)
from .managed_mutation import (
    AuthorityReservationSettlementPort,
    FixtureManagedMutationExecutor,
    FreshMutationAuthorityPort,
    ManagedMutationRuntimeError,
    MutationFaultHook,
    RuntimeAuthorityReservation,
    RuntimeIdentityAttestor,
    RuntimeKillSwitch,
    TrustedRuntimeClock,
    W04MutationAuthorityAdapter,
)
from .migration import (
    MIGRATION_ACTIVATION_RECORD_VERSION,
    MIGRATION_DB_VERSION,
    MIGRATION_ROLLBACK_RECORD_VERSION,
    PARITY_VERIFIER_RECORD_VERSION,
    DurableReadOnlyMigrationRuntime,
    FixturePinnedParityVerifier,
    MigrationActivationRequest,
    MigrationApprovalVerification,
    MigrationPolicy,
    MigrationRuntimeError,
    PinnedParityCase,
    ProjectionParityVerification,
    ReadOnlyProjectionSelection,
    TrustedMigrationApprovalVerifier,
    TrustedProjectionParityVerifier,
)
from .publisher import (
    PUBLICATION_WORKSPACE_VERIFICATION_VERSION,
    DurablePublicationRuntime,
    FixturePublicationWorkspaceVerifier,
    FixturePublisherPort,
    PublicationRuntimeError,
    PublicationRuntimeInputs,
    PublicationWorkspaceVerification,
    PublicationWorkspaceVerifier,
    publication_scope_references,
    release_assessment_bytes_sha256,
)


__all__ = [
    "CONTENT_EVIDENCE_VERSION",
    "ClaimBoundAuthorizationLedger",
    "ClaimBoundLedgerAdapter",
    "CREDENTIAL_ATTESTATION_VERSION",
    "CREDENTIAL_VERIFICATION_VERSION",
    "CredentialLease",
    "CredentialRuntimeError",
    "CredentialScope",
    "ContentAddressedFixtureStore",
    "AuthorityReservationSettlementPort",
    "AuthorityReservationClaim",
    "DurableDispatchInputs",
    "DurableExecutionError",
    "DurableExecutorRuntime",
    "DurablePublicationRuntime",
    "DurableReadOnlyMigrationRuntime",
    "ExecutionJournalError",
    "FixtureRuntimeBoundary",
    "FixtureAtomicMutationPort",
    "FixtureAuthoritySettlementStore",
    "FixtureWorkspaceObserver",
    "FixtureManagedMutationExecutor",
    "FixtureExecutorPort",
    "VerifiedExecutorInput",
    "VerifiedExecutorInputBundle",
    "FixtureCredentialBroker",
    "FixtureCredentialRegistration",
    "FixturePublicationWorkspaceVerifier",
    "FixturePublisherPort",
    "FixturePinnedParityVerifier",
    "FreshMutationAuthorityPort",
    "JournalSnapshot",
    "MANIFEST_VERSION",
    "MIGRATION_ACTIVATION_RECORD_VERSION",
    "MIGRATION_DB_VERSION",
    "MIGRATION_ROLLBACK_RECORD_VERSION",
    "PARITY_VERIFIER_RECORD_VERSION",
    "PUBLICATION_WORKSPACE_VERIFICATION_VERSION",
    "PublicationRuntimeError",
    "PublicationRuntimeInputs",
    "PublicationWorkspaceVerification",
    "PublicationWorkspaceVerifier",
    "RESULT_VERSION",
    "RuntimeBoundaryError",
    "RuntimeFilesystemError",
    "ManagedMutationRuntimeError",
    "MigrationActivationRequest",
    "MigrationApprovalVerification",
    "MigrationPolicy",
    "MigrationRuntimeError",
    "MutationFaultHook",
    "PinnedParityCase",
    "OpaqueCredentialHandle",
    "ProjectionParityVerification",
    "RuntimeAuthorityReservation",
    "RuntimeIdentityAttestor",
    "RuntimeKillSwitch",
    "ReadOnlyProjectionSelection",
    "SQLiteExecutionJournal",
    "StableFile",
    "TrustedRuntimeClock",
    "TrustedCredentialBroker",
    "TrustedMigrationApprovalVerifier",
    "TrustedProjectionParityVerifier",
    "W04MutationAuthorityAdapter",
    "fixture_manifest_sha256",
    "credential_scope_sha256",
    "journal_event_reference",
    "publication_scope_references",
    "read_stable_regular_file",
    "read_stable_regular_bytes",
    "release_assessment_bytes_sha256",
    "require_current_credential_lease",
]
