"""Operational CLI: command registry, recovery contracts, and honest stubs."""

from .handlers import (
    CommandNotYetBackedError,
    CommandResult,
    DoctorReport,
    ValidateReport,
    handle_approve,
    handle_doctor,
    handle_export,
    handle_init,
    handle_invalidate,
    handle_new_channel,
    handle_new_concept,
    handle_new_episode,
    handle_not_yet_backed,
    handle_qc,
    handle_reopen,
    handle_resume,
    handle_retry,
    handle_review,
    handle_run,
    handle_status,
    handle_validate,
    run_doctor,
    run_validate,
    run_validate_artifact,
    run_validate_artifact_directory,
)
from .main import build_parser, dispatch, main
from .recovery import (
    DEFAULT_RETRY_LEDGER,
    RecoveryAcceptance,
    RecoveryContractResult,
    RecoveryIntent,
    RecoveryPolicyError,
    RetryIdempotencyLedger,
    assert_recovery_command_permitted,
    request_invalidate,
    request_reopen,
    request_resume,
    request_retry,
)
from .registry import COMMAND_REGISTRY, COMMAND_SPECS, get_command, list_commands, registered_names
from .specs import CommandSpec, ImplementationStatus

__all__ = [
    "COMMAND_REGISTRY",
    "COMMAND_SPECS",
    "CommandNotYetBackedError",
    "CommandResult",
    "CommandSpec",
    "DEFAULT_RETRY_LEDGER",
    "DoctorReport",
    "ImplementationStatus",
    "RecoveryAcceptance",
    "RecoveryContractResult",
    "RecoveryIntent",
    "RecoveryPolicyError",
    "RetryIdempotencyLedger",
    "ValidateReport",
    "assert_recovery_command_permitted",
    "build_parser",
    "dispatch",
    "get_command",
    "handle_approve",
    "handle_doctor",
    "handle_export",
    "handle_init",
    "handle_invalidate",
    "handle_new_channel",
    "handle_new_concept",
    "handle_new_episode",
    "handle_not_yet_backed",
    "handle_qc",
    "handle_reopen",
    "handle_resume",
    "handle_retry",
    "handle_review",
    "handle_run",
    "handle_status",
    "handle_validate",
    "list_commands",
    "main",
    "registered_names",
    "request_invalidate",
    "request_reopen",
    "request_resume",
    "request_retry",
    "run_doctor",
    "run_validate",
    "run_validate_artifact",
    "run_validate_artifact_directory",
]
